name: Old Apps Testing
on:
  workflow_dispatch:
    
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - baseUrl: ‘https://release-ee-mongo.appsmith.com/’
            specs: ‘cypress/e2e/OldAppTesting/release-ee-mongo/**/*.{js,ts}’
          - baseUrl: ‘https://nightly-saml-alb-https.appsmith.com/’
            specs: ‘cypress/e2e/OldAppTesting/nightlysaml/**/*.{js,ts}’
    name: Cypress Tests - ${{ matrix.baseUrl }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: app/client/package.json
      - name: Install dependencies
        working-directory: app/client
        run: |
          yarn install --immutable
      - name: Setting up the cypress tests
        if: steps.run_result.outputs.run_result != 'success'
        shell: bash
        run: |
          cd app/client
          chmod a+x ./cypress/setup-test-ci.sh
          ./cypress/setup-test-ci.sh
          
      - name: Install Google Chrome 129.0.6668.100
        run: |
          sudo apt-get remove google-chrome-stable
          wget -q https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_129.0.6668.100-1_amd64.deb
          sudo apt-get update
          sudo apt-get install -y ./google-chrome-stable_129.0.6668.100-1_amd64.deb
          echo "BROWSER_PATH=$(which google-chrome)" >> $GITHUB_ENV
          google-chrome --version

      - name: Run the cypress test
        uses: cypress-io/github-action@v6
        env:
          GITHUB_TOKEN: ""
          CYPRESS_USERNAME: ${{ secrets.OLD_APP_TESTING_USER }}
          CYPRESS_PASSWORD: ${{ secrets.OLD_APP_TESTING_PWD }}
          CYPRESS_TESTUSERNAME1: ""
          CYPRESS_TESTPASSWORD1: ""
          CYPRESS_TESTUSERNAME2: ""
          CYPRESS_TESTPASSWORD2: ""
          CYPRESS_EXCLUDE_TAGS: "airgap"
          CYPRESS_AIRGAPPED: false
          APPSMITH_DISABLE_TELEMETRY: true
          CYPRESS_VERIFY_TIMEOUT: 100000
          RUNID: ${{ github.run_id }}
          ATTEMPT_NUMBER: ${{ github.run_attempt }}
          REPOSITORY: ${{ github.repository }}
          COMMITTER: ${{ env.COMMIT_INFO_AUTHOR }}
          TAG: ${{ github.event_name }}
          BRANCH: ${{ env.COMMIT_INFO_BRANCH }}
          CYPRESS_SPECS: ${{ matrix.specs }}
          CYPRESS_RERUN: ${{steps.run_result.outputs.rerun}}
          CYPRESS_STATIC_ALLOCATION: true
        with:
          browser: ${{ env.BROWSER_PATH }}
          install: false
          config-file: cypress_ci_custom.config.ts
          spec: ${{ matrix.specs }}
          working-directory: app/client
          env: "NODE_ENV=development"
