name: Old Apps Testing
on:
  workflow_dispatch:
    
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - baseUrl: ‘https://release-ee-mongo.appsmith.com/’
            specs: ‘cypress/e2e/OldAppTesting/release-ee-mongo/**/*.{js,ts}’
          - baseUrl: ‘https://nightly-saml-alb-https.appsmith.com/’
            specs: ‘cypress/e2e/OldAppTesting/nightlysaml/**/*.{js,ts}’
    name: Cypress Tests - ${{ matrix.baseUrl }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: app/client/package.json
      - name: Install dependencies
        working-directory: app/client
        run: |
          yarn install --immutable
      - name: Update Cypress config
        run: |
          sed -i “s|baseUrl: \“.*\“|baseUrl: \“${{ matrix.baseUrl }}\“|” app/client/cypress.config.ts
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_USERNAME: ${{ secrets.OLD_APP_TESTING_USER }}
          CYPRESS_PASSWORD: ${{ secrets.OLD_APP_TESTING_PWD }}
        with:
          browser: chrome
          build: npm run build
          start: npm start
          wait-on: ${{ matrix.baseUrl }}
          config-file: app/client/cypress.config.ts
          spec: ${{ matrix.specs }}
